# Generated by Django 5.2.8 on 2025-11-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('department', models.CharField(choices=[('IT', 'IT'), ('CSE', 'CSE'), ('EEE', 'EEE'), ('ECE', 'ECE')])),
                ('marks', models.PositiveIntegerField(max_length=100)),
                ('attendance', models.PositiveIntegerField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('city', models.CharField()),
                ('mentor', models.CharField()),
                ('fees_paid', models.PositiveIntegerField()),
            ],
        ),
    ]
