# Generated by Django 5.2.8 on 2025-11-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('Author', models.CharField()),
                ('Category', models.CharField(choices=[('Fiction', 'Fiction'), ('Science', 'Science'), ('History', 'History')])),
                ('Price', models.PositiveIntegerField()),
                ('published_date', models.DateField()),
                ('is_available', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')])),
            ],
        ),
    ]
